site_name: My Docs
nav:
  - Home: index.md
  - Introduction: code_introduction.md
  - About: about.md
theme: rtd-dropdown
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
